name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
  schedule:
    - cron: "3 3 * * 2" # 3:03 AM, every Tuesday

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macOS:
    name: ${{ matrix.platform }} (Swift ${{ matrix.swift }})
    runs-on: macos-15
    strategy:
      fail-fast: false
      matrix:
        platform:
          - iOS
          - macOS
          - tvOS
          - watchOS
        swift:
          - "6.0"
          - "6.1"
          - "6.2"
        include:
          - action: test
    steps:
      - uses: actions/checkout@v4
      - uses: mxcl/xcodebuild@v3
        with:
          action: ${{ matrix.action }}
          platform: ${{ matrix.platform }}
          swift: ~${{ matrix.swift }}
          workspace: Builders.xcworkspace
          scheme: Builders
  linux:
    name: Linux (Swift ${{ matrix.swift }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        swift:
          - "6.0"
          - "6.1"
          - "6.2"
    container:
      image: swift:${{ matrix.swift }}
    steps:
      - uses: actions/checkout@v4
      - run: swift test --parallel --sanitize=thread -Xswiftc -warnings-as-errors
